#!/bin/sh
# By Elijah Z Granet on 12 June 2015.
# Description: OCR pdfs
export PATH=$PATH:/opt/homebrew/bin
consoleUser() {
    echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ && ! /loginwindow/ { print $3 }'
}

displayfortext() { # $1: message $2: default text
	message=${1:-"Message"}
	defaultvalue=${2:-"default value"}
	user=$(consoleUser)
    if [[ $user != "" ]]; then
        uid=$(id -u "$user")
	
	    launchctl asuser $uid /usr/bin/osascript <<-EndOfScript
			text returned of ¬
				(display dialog "$message" ¬
					default answer "$defaultvalue" ¬
					buttons {"OK"} ¬
					default button "OK")
			EndOfScript
	else
	    exit 1
	fi
}


if [ $# == 0 ] ; then
    echo "Drag a PDF to the window or click File -> Open.  Remember to install the dependencies first!"
    exit 1;
fi
lang=$(displayfortext "What language(s) are these in? Enter the three letter codes, separated by the + sign. For example, a document in  English and French would be eng+fra ; these codes can be found online at https://tesseract-ocr.github.io/tessdoc/Data-Files-in-different-versions.html" "eng")
for path in "$@"
do
ocrmypdf -l "$lang" "$path" "$path"-ocr.pdf --force-ocr; 
done
osascript -e 'display notification "OCR Completed!"'; echo "OCR Completed.!"